import type { Conexion, Grupo } from "../tipos";

export const GRUPOS: Grupo[] = [
  {
    id: "gr-1",
    nombre: "Holguineros en cualquier parte",
    categoria: "Provincia cubana",
    descripcion: "Gente de Holguín dentro y fuera de la Isla, con ayuda entre vecinos.",
    miembros: 1042,
    privacidad: "abierto",
    zona: "Holguín · Internacional",
    actividad: "12 publicaciones esta semana",
    unido: true,
  },
  {
    id: "gr-2",
    nombre: "Madres que emprenden",
    categoria: "Emprendimiento",
    descripcion: "Ideas, precios, proveedores y apoyo entre mujeres con negocio propio.",
    miembros: 786,
    privacidad: "solicitud",
    zona: "Cuba",
    actividad: "30 publicaciones esta semana",
    unido: false,
  },
  {
    id: "gr-3",
    nombre: "Cubanos en Madrid",
    categoria: "País",
    descripcion: "Trámites, alquiler, trabajo y encuentros para recién llegados.",
    miembros: 2314,
    privacidad: "abierto",
    zona: "Madrid, España",
    actividad: "45 publicaciones esta semana",
    unido: false,
  },
  {
    id: "gr-4",
    nombre: "Maestros de primaria",
    categoria: "Profesión",
    descripcion: "Material de aula, ideas de clase y apoyo profesional.",
    miembros: 512,
    privacidad: "solicitud",
    zona: "Cuba",
    actividad: "9 publicaciones esta semana",
    unido: true,
  },
  {
    id: "gr-5",
    nombre: "Cocina cubana de verdad",
    categoria: "Cultura",
    descripcion: "Recetas de casa, sustituciones y trucos cuando falta un ingrediente.",
    miembros: 3980,
    privacidad: "abierto",
    zona: "Internacional",
    actividad: "60 publicaciones esta semana",
    unido: true,
  },
  {
    id: "gr-6",
    nombre: "Ayuda comunitaria Villa Clara",
    categoria: "Ayuda comunitaria",
    descripcion: "Coordinación de campañas y promotores en la provincia.",
    miembros: 431,
    privacidad: "privado",
    zona: "Villa Clara",
    actividad: "Actividad diaria",
    unido: false,
  },
  {
    id: "gr-7",
    nombre: "Estudiar desde Cuba",
    categoria: "Formación",
    descripcion: "Cursos, becas y grupos de estudio con poca conexión.",
    miembros: 1197,
    privacidad: "abierto",
    zona: "Cuba · Internacional",
    actividad: "18 publicaciones esta semana",
    unido: false,
  },
  {
    id: "gr-8",
    nombre: "Familias a dos orillas",
    categoria: "Familia",
    descripcion: "Cómo sostener el vínculo cuando la familia está repartida.",
    miembros: 905,
    privacidad: "solicitud",
    zona: "Internacional",
    actividad: "22 publicaciones esta semana",
    unido: false,
  },
  {
    id: "gr-9",
    nombre: "Vedado y alrededores",
    categoria: "Ciudad",
    descripcion: "Lo que pasa en el barrio: agua, transporte, ventas y ayuda.",
    miembros: 664,
    privacidad: "abierto",
    zona: "La Habana",
    actividad: "27 publicaciones esta semana",
    unido: false,
  },
];

export const CONEXIONES: Conexion[] = [
  {
    alias: "guajiroconwifi",
    nombreVisible: "guajiroconwifi",
    avatar: "RP",
    detalle: "Sancti Spíritus · Mecánica y transporte",
    relacion: "conexion",
  },
  {
    alias: "solarhabana",
    nombreVisible: "Lisbet Ferrer",
    avatar: "LF",
    detalle: "La Habana · Diseño y formación",
    relacion: "conexion",
  },
  {
    alias: "cafeconletras",
    nombreVisible: "cafeconletras",
    avatar: "EV",
    detalle: "La Habana · Opinión y economía",
    relacion: "sigues",
  },
  {
    alias: "manosdealtamar",
    nombreVisible: "Dayana Cruz",
    avatar: "DC",
    detalle: "Sevilla · Promotora internacional",
    relacion: "sigues",
  },
  {
    alias: "orillanorte",
    nombreVisible: "orillanorte",
    avatar: "MT",
    detalle: "Miami · Empleo y mentoría",
    relacion: "seguidor",
  },
  {
    alias: "manosdebaracoa",
    nombreVisible: "Manos de Baracoa",
    avatar: "MB",
    detalle: "Baracoa · Artesanía",
    relacion: "invitacion",
  },
  {
    alias: "esquina-yoel",
    nombreVisible: "Café La Esquina",
    avatar: "CE",
    detalle: "Santa Clara · Cafetería de barrio",
    relacion: "sugerencia",
  },
  {
    alias: "almendares-osmany",
    nombreVisible: "Taller Almendares",
    avatar: "TA",
    detalle: "La Habana · Reparaciones",
    relacion: "sugerencia",
  },
];
