import type { Negocio } from "../tipos";

export const NEGOCIOS: Negocio[] = [
  {
    slug: "mango-y-miel",
    nombre: "Mango y Miel",
    descripcion:
      "Taller familiar de mermeladas y conservas de fruta de temporada. Trabajamos con productores de la zona y devolvemos el frasco al ciclo.",
    sector: "Alimentación",
    pais: "Cuba",
    area: "Matanzas",
    logoTexto: "MM",
    verificado: true,
    solidario: true,
    productos: ["Mermelada de mango", "Conserva de guayaba", "Miel de la zona"],
    representantes: [
      { nombreVisible: "Idalmis", papel: "Fundadora", alias: "mangoymiel-ida" },
      { nombreVisible: "Yandy", papel: "Producción", alias: "mangoymiel-yandy" },
    ],
    empleos: 2,
    proyectos: [
      {
        titulo: "Merienda escolar",
        detalle: "Aportamos conservas a la campaña del aula de tercer grado.",
      },
    ],
    insignias: ["Negocio verificado", "Negocio solidario"],
    contacto: ["Mensaje dentro de La Chivichana", "Formulario de pedidos"],
    impacto: [
      { dato: "2", texto: "Empleos creados este año" },
      { dato: "1", texto: "Campaña apoyada" },
    ],
    colaboracion: "Buscamos quien nos ayude con el etiquetado y con transporte hacia La Habana.",
  },
  {
    slug: "taller-almendares",
    nombre: "Taller Almendares",
    descripcion:
      "Reparación de electrodomésticos pequeños. Diagnóstico gratuito y mano de obra gratis para personas mayores del municipio.",
    sector: "Servicios técnicos",
    pais: "Cuba",
    area: "La Habana",
    logoTexto: "TA",
    verificado: true,
    solidario: true,
    productos: [
      "Reparación de ventiladores",
      "Reparación de batidoras",
      "Mantenimiento de ollas eléctricas",
    ],
    representantes: [
      { nombreVisible: "Osmany", papel: "Responsable de taller", alias: "almendares-osmany" },
    ],
    empleos: 1,
    proyectos: [
      {
        titulo: "Ventiladores para mayores",
        detalle: "14 reparaciones gratuitas registradas por número de orden.",
      },
    ],
    insignias: ["Negocio verificado", "Promotor empresarial"],
    contacto: ["Mensaje dentro de La Chivichana"],
    impacto: [
      { dato: "14", texto: "Reparaciones solidarias este mes" },
      { dato: "209", texto: "Valoraciones de clientes" },
    ],
    colaboracion: "Aceptamos donación de piezas y aprendices que quieran formarse.",
  },
  {
    slug: "manos-de-baracoa",
    nombre: "Manos de Baracoa",
    descripcion: "Cooperativa de artesanas que teje en fibras naturales de la zona oriental.",
    sector: "Artesanía",
    pais: "Cuba",
    area: "Baracoa, Guantánamo",
    logoTexto: "MB",
    verificado: false,
    solidario: false,
    productos: ["Cestas de guano", "Sombreros", "Individuales de mesa"],
    representantes: [{ nombreVisible: "Nurys", papel: "Coordinadora", alias: "baracoa-nurys" }],
    empleos: 0,
    proyectos: [],
    insignias: ["Verificación en trámite"],
    contacto: ["Mensaje dentro de La Chivichana"],
    impacto: [{ dato: "9", texto: "Artesanas en la cooperativa" }],
    colaboracion: "Buscamos ayuda con fotografía de producto y catálogo digital.",
  },
  {
    slug: "dos-orillas-envios",
    nombre: "Dos Orillas Envíos",
    descripcion:
      "Empresa de logística fundada por cubanos en Madrid. Trabaja con promotores acreditados en la Isla.",
    sector: "Logística",
    pais: "España",
    area: "Madrid · enlaces en La Habana y Santa Clara",
    logoTexto: "DO",
    verificado: true,
    solidario: true,
    productos: ["Envío de paquetes", "Transporte de insumos para campañas"],
    representantes: [{ nombreVisible: "Michel", papel: "Dirección", alias: "orillanorte" }],
    empleos: 3,
    proyectos: [
      {
        titulo: "Transporte solidario",
        detalle: "Cubrimos el transporte de dos campañas de La Mano al mes.",
      },
    ],
    insignias: ["Negocio verificado", "Negocio solidario"],
    contacto: ["Mensaje dentro de La Chivichana", "Formulario de colaboración"],
    impacto: [
      { dato: "2", texto: "Campañas transportadas al mes" },
      { dato: "3", texto: "Empleos a cubanos recién llegados" },
    ],
    colaboracion: "Ofrecemos mentoría de logística a negocios pequeños de la Isla.",
  },
  {
    slug: "cafe-la-esquina",
    nombre: "Café La Esquina",
    descripcion: "Cafetería de barrio con precios diferenciados para vecinos mayores.",
    sector: "Gastronomía",
    pais: "Cuba",
    area: "Santa Clara",
    logoTexto: "CE",
    verificado: false,
    solidario: true,
    productos: ["Café", "Dulces caseros", "Meriendas"],
    representantes: [{ nombreVisible: "Yoel", papel: "Propietario", alias: "esquina-yoel" }],
    empleos: 2,
    proyectos: [
      { titulo: "Café suspendido", detalle: "Quien quiere deja pagado un café para otra persona." },
    ],
    insignias: ["Negocio solidario"],
    contacto: ["Mensaje dentro de La Chivichana"],
    impacto: [{ dato: "70", texto: "Cafés suspendidos entregados" }],
    colaboracion: "Buscamos proveedores estables de leche y azúcar.",
  },
  {
    slug: "estudio-solar",
    nombre: "Estudio Solar",
    descripcion: "Pequeño estudio de diseño gráfico y formación en herramientas digitales.",
    sector: "Diseño",
    pais: "Cuba",
    area: "La Habana",
    logoTexto: "ES",
    verificado: true,
    solidario: false,
    productos: ["Identidad para negocios", "Carteles", "Clases de diseño"],
    representantes: [{ nombreVisible: "Lisbet Ferrer", papel: "Diseñadora", alias: "solarhabana" }],
    empleos: 1,
    proyectos: [
      {
        titulo: "Clases gratis los sábados",
        detalle: "Formación abierta a vecinas emprendedoras.",
      },
    ],
    insignias: ["Negocio verificado"],
    contacto: ["Mensaje dentro de La Chivichana"],
    impacto: [{ dato: "8", texto: "Negocios con imagen nueva" }],
    colaboracion: "Intercambiamos diseño por formación en contabilidad.",
  },
];

export function buscarNegocio(slug: string) {
  return NEGOCIOS.find((n) => n.slug === slug);
}
