import type { Articulo } from "../tipos";

export const CATEGORIAS_MERCADITO = [
  "Alimentos",
  "Ropa",
  "Hogar",
  "Tecnología",
  "Transporte",
  "Servicios",
  "Artesanía",
  "Formación",
  "Regalos y donaciones",
];

export const ARTICULOS: Articulo[] = [
  {
    id: "art-1",
    titulo: "Mermelada artesanal de mango (frasco de 350 g)",
    descripcion:
      "Hecha con mango de temporada de Matanzas, sin colorantes. Se entrega en frasco de cristal retornable; si devuelves el frasco te descontamos la próxima compra.",
    categoria: "Alimentos",
    modo: "venta",
    precio: 450,
    moneda: "CUP",
    estado: "nuevo",
    zona: "Matanzas, Cuba",
    publicado: "hace 3 horas",
    imagenAlt: "Frascos de mermelada de mango sobre una mesa de madera",
    vendedor: {
      alias: "mango-y-miel",
      nombreVisible: "Mango y Miel",
      avatar: "MM",
      verificado: true,
      reputacion: 4.9,
      valoraciones: 132,
      desde: "febrero de 2026",
      tipo: "negocio",
    },
    entrega: "Recogida en el taller o mensajería local acordada por mensaje",
    interesados: 41,
  },
  {
    id: "art-2",
    titulo: "Ropa de niño de 4 a 6 años en buen estado",
    descripcion:
      "Lote de doce piezas: pulóveres, shorts y dos uniformes. Está limpio y planchado. Lo doy gratis a quien lo necesite; prefiero que sea para una casa con varios niños.",
    categoria: "Regalos y donaciones",
    modo: "donacion",
    estado: "usado",
    zona: "Cienfuegos, Cuba",
    publicado: "hace 6 horas",
    imagenAlt: "Ropa infantil doblada dentro de una caja de cartón",
    vendedor: {
      alias: "vientodelsur",
      nombreVisible: "vientodelsur",
      avatar: "YM",
      verificado: true,
      reputacion: 5,
      valoraciones: 18,
      desde: "marzo de 2026",
      tipo: "alias",
    },
    entrega: "Se coordina un punto público en el centro de la ciudad",
    interesados: 23,
  },
  {
    id: "art-3",
    titulo: "Bicicleta eléctrica restaurada con batería nueva",
    descripcion:
      "Cuadro reforzado, frenos revisados, luces delanteras y traseras funcionando. Autonomía aproximada de 40 km. Acepto cambio por nevera pequeña en buen estado.",
    categoria: "Transporte",
    modo: "intercambio",
    precio: 62000,
    moneda: "CUP",
    estado: "como-nuevo",
    zona: "Sancti Spíritus, Cuba",
    publicado: "hace 2 horas",
    imagenAlt: "Bicicleta eléctrica restaurada apoyada en un portal",
    vendedor: {
      alias: "guajiroconwifi",
      nombreVisible: "guajiroconwifi",
      avatar: "RP",
      verificado: false,
      reputacion: 4.6,
      valoraciones: 27,
      desde: "abril de 2026",
      tipo: "alias",
    },
    entrega: "Se prueba en persona antes de cerrar el trato",
    interesados: 74,
  },
  {
    id: "art-4",
    titulo: "Reparación de ventiladores y equipos pequeños",
    descripcion:
      "Diagnóstico gratuito. Reparo ventiladores, batidoras y ollas eléctricas. Para personas mayores del municipio, la mano de obra es gratis.",
    categoria: "Servicios",
    modo: "servicio",
    precio: 900,
    moneda: "CUP",
    estado: "no-aplica",
    zona: "La Habana, Cuba",
    publicado: "hace 1 día",
    imagenAlt: "Mesa de taller con herramientas y un ventilador desarmado",
    vendedor: {
      alias: "taller-almendares",
      nombreVisible: "Taller Almendares",
      avatar: "TA",
      verificado: true,
      reputacion: 4.8,
      valoraciones: 209,
      desde: "enero de 2026",
      tipo: "negocio",
    },
    entrega: "En el taller, de lunes a sábado",
    interesados: 55,
  },
  {
    id: "art-5",
    titulo: "Clases de matemáticas para noveno grado",
    descripcion:
      "Repaso de álgebra y geometría, en grupos de tres. Primera clase de prueba sin costo para ver si nos entendemos.",
    categoria: "Formación",
    modo: "servicio",
    precio: 700,
    moneda: "CUP",
    estado: "no-aplica",
    zona: "Cienfuegos, Cuba",
    publicado: "hace 8 horas",
    imagenAlt: "Pizarra pequeña con ejercicios de álgebra resueltos",
    vendedor: {
      alias: "vientodelsur",
      nombreVisible: "vientodelsur",
      avatar: "YM",
      verificado: true,
      reputacion: 5,
      valoraciones: 18,
      desde: "marzo de 2026",
      tipo: "alias",
    },
    entrega: "Presencial en casa de la maestra o por videollamada",
    interesados: 31,
  },
  {
    id: "art-6",
    titulo: "Cesta tejida a mano en guano natural",
    descripcion:
      "Tejida en Baracoa con guano curado. Sirve para pan, costura o ropa. Cada pieza sale distinta porque se hace a mano.",
    categoria: "Artesanía",
    modo: "venta",
    precio: 2200,
    moneda: "CUP",
    estado: "nuevo",
    zona: "Baracoa, Cuba",
    publicado: "hace 2 días",
    imagenAlt: "Cesta redonda tejida en fibra vegetal clara",
    vendedor: {
      alias: "manosdebaracoa",
      nombreVisible: "Manos de Baracoa",
      avatar: "MB",
      verificado: false,
      reputacion: 4.7,
      valoraciones: 44,
      desde: "mayo de 2026",
      tipo: "negocio",
    },
    entrega: "Envío nacional por mensajería acordada",
    interesados: 19,
  },
  {
    id: "art-7",
    titulo: "Teléfono usado con pantalla sana",
    descripcion:
      "Funciona bien, la batería dura media jornada. Lo cambio por datos móviles o por una impresora que sirva.",
    categoria: "Tecnología",
    modo: "intercambio",
    estado: "usado",
    zona: "Santa Clara, Cuba",
    publicado: "hace 4 horas",
    imagenAlt: "Teléfono móvil usado sobre una mesa",
    vendedor: {
      alias: "orillanorte",
      nombreVisible: "orillanorte",
      avatar: "MT",
      verificado: false,
      reputacion: 4.4,
      valoraciones: 12,
      desde: "marzo de 2026",
      tipo: "alias",
    },
    entrega: "Entrega en mano en punto público",
    interesados: 62,
  },
  {
    id: "art-8",
    titulo: "Juego de sábanas de algodón",
    descripcion: "Cama camera, dos fundas incluidas. Poco uso, sin manchas ni roturas.",
    categoria: "Hogar",
    modo: "venta",
    precio: 3800,
    moneda: "CUP",
    estado: "como-nuevo",
    zona: "La Habana, Cuba",
    publicado: "hace 1 día",
    imagenAlt: "Juego de sábanas dobladas de color claro",
    vendedor: {
      alias: "solarhabana",
      nombreVisible: "Lisbet Ferrer",
      avatar: "LF",
      verificado: false,
      reputacion: 4.8,
      valoraciones: 36,
      desde: "mayo de 2026",
      tipo: "nombre",
    },
    entrega: "Recogida en el barrio o punto acordado",
    interesados: 14,
  },
  {
    id: "art-9",
    titulo: "Uniformes escolares de segunda mano",
    descripcion:
      "Cinco uniformes de secundaria en buen estado. Los regalo a familias del barrio; si sobran, van para la escuela.",
    categoria: "Ropa",
    modo: "donacion",
    estado: "usado",
    zona: "Holguín, Cuba",
    publicado: "hace 3 días",
    imagenAlt: "Uniformes escolares colgados en perchas",
    vendedor: {
      alias: "manosdealtamar",
      nombreVisible: "Dayana Cruz",
      avatar: "DC",
      verificado: true,
      reputacion: 5,
      valoraciones: 88,
      desde: "febrero de 2026",
      tipo: "nombre",
    },
    entrega: "Coordinado con un promotor de la zona",
    interesados: 27,
  },
];

export function buscarArticulo(id: string) {
  return ARTICULOS.find((a) => a.id === id);
}