import type { Anunciante, Articulo } from "../tipos";

export const CATEGORIAS_MERCADITO = [
  "Alimentos",
  "Ropa y calzado",
  "Hogar",
  "Tecnología",
  "Transporte",
  "Servicios",
  "Artesanía",
  "Formación",
  "Herramientas",
  "Salud y bienestar",
  "Regalos y donaciones",
  "Otros",
];

export const PAISES_MERCADITO = ["Cuba", "España", "Estados Unidos", "México"];

export const ESTADOS_ARTICULO = [
  { valor: "nuevo", texto: "Nuevo" },
  { valor: "como-nuevo", texto: "Como nuevo" },
  { valor: "usado", texto: "Usado" },
  { valor: "para-piezas", texto: "Para piezas" },
  { valor: "no-aplica", texto: "No aplica" },
] as const;

export const ENTREGAS_SUGERIDAS = [
  "Recogida en punto público acordado",
  "Mensajería local acordada por mensaje",
  "Entrega en el taller o local",
  "Envío nacional por mensajería",
  "Por videollamada",
];

const ANUNCIANTES = {
  mangoYMiel: {
    alias: "mango-y-miel",
    nombreVisible: "Mango y Miel",
    avatar: "MM",
    verificado: true,
    reputacion: 4.9,
    valoraciones: 132,
    desde: "febrero de 2026",
    tipo: "negocio",
    operaciones: 148,
    tiempoRespuesta: "Suele responder en menos de 2 horas",
    enlace: "/negocio/mango-y-miel",
  },
  vientodelsur: {
    alias: "vientodelsur",
    nombreVisible: "vientodelsur",
    avatar: "YM",
    verificado: true,
    reputacion: 5,
    valoraciones: 18,
    desde: "marzo de 2026",
    tipo: "alias",
    operaciones: 21,
    tiempoRespuesta: "Suele responder el mismo día",
    enlace: "/perfil/vientodelsur",
  },
  guajiro: {
    alias: "guajiroconwifi",
    nombreVisible: "guajiroconwifi",
    avatar: "RP",
    verificado: false,
    reputacion: 4.6,
    valoraciones: 27,
    desde: "abril de 2026",
    tipo: "alias",
    operaciones: 30,
    tiempoRespuesta: "Suele responder en un día",
    enlace: "/perfil/guajiroconwifi",
  },
  taller: {
    alias: "taller-almendares",
    nombreVisible: "Taller Almendares",
    avatar: "TA",
    verificado: true,
    reputacion: 4.8,
    valoraciones: 209,
    desde: "enero de 2026",
    tipo: "negocio",
    operaciones: 231,
    tiempoRespuesta: "Suele responder en menos de 3 horas",
    enlace: "/negocio/taller-almendares",
  },
  baracoa: {
    alias: "manosdebaracoa",
    nombreVisible: "Manos de Baracoa",
    avatar: "MB",
    verificado: false,
    reputacion: 4.7,
    valoraciones: 44,
    desde: "mayo de 2026",
    tipo: "negocio",
    operaciones: 52,
    tiempoRespuesta: "Suele responder en dos días",
    enlace: "/negocio/manos-de-baracoa",
  },
  orillanorte: {
    alias: "orillanorte",
    nombreVisible: "orillanorte",
    avatar: "MT",
    verificado: false,
    reputacion: 4.4,
    valoraciones: 12,
    desde: "marzo de 2026",
    tipo: "alias",
    operaciones: 14,
    tiempoRespuesta: "Suele responder en un día",
    enlace: "/perfil/orillanorte",
  },
  solarhabana: {
    alias: "solarhabana",
    nombreVisible: "Lisbet Ferrer",
    avatar: "LF",
    verificado: false,
    reputacion: 4.8,
    valoraciones: 36,
    desde: "mayo de 2026",
    tipo: "nombre",
    operaciones: 39,
    tiempoRespuesta: "Suele responder el mismo día",
    enlace: "/perfil/solarhabana",
  },
  altamar: {
    alias: "manosdealtamar",
    nombreVisible: "Dayana Cruz",
    avatar: "DC",
    verificado: true,
    reputacion: 5,
    valoraciones: 88,
    desde: "febrero de 2026",
    tipo: "nombre",
    operaciones: 92,
    tiempoRespuesta: "Suele responder en pocas horas",
    enlace: "/perfil/manosdealtamar",
  },
  dosOrillas: {
    alias: "dos-orillas-envios",
    nombreVisible: "Dos Orillas Envíos",
    avatar: "DO",
    verificado: true,
    reputacion: 4.7,
    valoraciones: 164,
    desde: "enero de 2026",
    tipo: "negocio",
    operaciones: 180,
    tiempoRespuesta: "Suele responder en menos de 1 hora",
    enlace: "/negocio/dos-orillas-envios",
  },
  cafeconletras: {
    alias: "cafeconletras",
    nombreVisible: "Ernesto Valdés",
    avatar: "EV",
    verificado: true,
    reputacion: 4.9,
    valoraciones: 57,
    desde: "marzo de 2026",
    tipo: "nombre",
    operaciones: 60,
    tiempoRespuesta: "Suele responder el mismo día",
    enlace: "/perfil/cafeconletras",
  },
} satisfies Record<string, Anunciante>;

export const ARTICULOS: Articulo[] = [
  {
    id: "art-1",
    titulo: "Mermelada artesanal de mango (frasco de 350 g)",
    descripcion:
      "Hecha con mango de temporada de Matanzas, sin colorantes. Se entrega en frasco de cristal retornable; si devuelves el frasco te descontamos la próxima compra.",
    categoria: "Alimentos",
    modo: "venta",
    precio: 450,
    moneda: "CUP",
    negociable: false,
    estado: "nuevo",
    zona: "Matanzas",
    pais: "Cuba",
    publicado: "hace 3 horas",
    imagenAlt: "Frascos de mermelada de mango sobre una mesa de madera",
    vendedor: ANUNCIANTES.mangoYMiel!,
    entrega: "Recogida en el taller o mensajería local acordada por mensaje",
    interesados: 41,
    vistas: 512,
    tono: "sol",
    estadoAnuncio: "activo",
  },
  {
    id: "art-2",
    titulo: "Ropa de niño de 4 a 6 años en buen estado",
    descripcion:
      "Lote de doce piezas: pulóveres, shorts y dos uniformes. Está limpio y planchado. Lo doy gratis a quien lo necesite; prefiero que sea para una casa con varios niños.",
    categoria: "Regalos y donaciones",
    modo: "donacion",
    estado: "usado",
    zona: "Cienfuegos",
    pais: "Cuba",
    publicado: "hace 6 horas",
    imagenAlt: "Ropa infantil doblada dentro de una caja de cartón",
    vendedor: ANUNCIANTES.vientodelsur!,
    entrega: "Se coordina un punto público en el centro de la ciudad",
    interesados: 23,
    vistas: 288,
    tono: "turquesa",
    estadoAnuncio: "activo",
    cantidad: "12 piezas",
    destinatario: "Familias con niños pequeños del municipio",
  },
  {
    id: "art-3",
    titulo: "Bicicleta eléctrica restaurada con batería nueva",
    descripcion:
      "Cuadro reforzado, frenos revisados, luces delanteras y traseras funcionando. Autonomía aproximada de 40 km. Acepto cambio por nevera pequeña en buen estado.",
    categoria: "Transporte",
    modo: "intercambio",
    estado: "como-nuevo",
    zona: "Sancti Spíritus",
    pais: "Cuba",
    publicado: "hace 2 horas",
    imagenAlt: "Bicicleta eléctrica restaurada apoyada en un portal",
    vendedor: ANUNCIANTES.guajiro!,
    entrega: "Se prueba en persona antes de cerrar el trato",
    interesados: 74,
    vistas: 934,
    tono: "mar",
    estadoAnuncio: "activo",
    ofrece: "Bicicleta eléctrica restaurada con batería nueva",
    busca: "Nevera pequeña en buen estado",
    alternativas: "También valoro una planta eléctrica pequeña o herramientas de carpintería",
  },
  {
    id: "art-4",
    titulo: "Reparación de ventiladores y equipos pequeños",
    descripcion:
      "Diagnóstico gratuito. Reparo ventiladores, batidoras y ollas eléctricas. Para personas mayores del municipio, la mano de obra es gratis.",
    categoria: "Servicios",
    modo: "servicio",
    precio: 900,
    moneda: "CUP",
    estado: "no-aplica",
    zona: "La Habana",
    pais: "Cuba",
    publicado: "hace 1 día",
    imagenAlt: "Mesa de taller con herramientas y un ventilador desarmado",
    vendedor: ANUNCIANTES.taller!,
    entrega: "En el taller, de lunes a sábado",
    interesados: 55,
    vistas: 771,
    tono: "madera",
    estadoAnuncio: "activo",
    tipoServicio: "Reparación de electrodomésticos",
    precioModo: "desde",
    lugar: "presencial",
    disponibilidad: "Lunes a sábado, de 9:00 a 17:00",
  },
  {
    id: "art-5",
    titulo: "Clases de matemáticas para noveno grado",
    descripcion:
      "Repaso de álgebra y geometría, en grupos de tres. Primera clase de prueba sin costo para ver si nos entendemos.",
    categoria: "Formación",
    modo: "servicio",
    precio: 700,
    moneda: "CUP",
    estado: "no-aplica",
    zona: "Cienfuegos",
    pais: "Cuba",
    publicado: "hace 8 horas",
    imagenAlt: "Pizarra pequeña con ejercicios de álgebra resueltos",
    vendedor: ANUNCIANTES.vientodelsur!,
    entrega: "Presencial en casa de la maestra o por videollamada",
    interesados: 31,
    vistas: 402,
    tono: "turquesa",
    estadoAnuncio: "activo",
    tipoServicio: "Clases particulares",
    precioModo: "fijo",
    lugar: "mixto",
    disponibilidad: "Tardes de martes, jueves y sábado",
  },
  {
    id: "art-6",
    titulo: "Cesta tejida a mano en guano natural",
    descripcion:
      "Tejida en Baracoa con guano curado. Sirve para pan, costura o ropa. Cada pieza sale distinta porque se hace a mano.",
    categoria: "Artesanía",
    modo: "venta",
    precio: 2200,
    moneda: "CUP",
    negociable: true,
    estado: "nuevo",
    zona: "Baracoa",
    pais: "Cuba",
    publicado: "hace 2 días",
    imagenAlt: "Cesta redonda tejida en fibra vegetal clara",
    vendedor: ANUNCIANTES.baracoa!,
    entrega: "Envío nacional por mensajería acordada",
    interesados: 19,
    vistas: 233,
    tono: "madera",
    estadoAnuncio: "activo",
  },
  {
    id: "art-7",
    titulo: "Teléfono usado con pantalla sana",
    descripcion:
      "Funciona bien, la batería dura media jornada. Lo cambio por datos móviles o por una impresora que sirva.",
    categoria: "Tecnología",
    modo: "intercambio",
    estado: "usado",
    zona: "Santa Clara",
    pais: "Cuba",
    publicado: "hace 4 horas",
    imagenAlt: "Teléfono móvil usado sobre una mesa",
    vendedor: ANUNCIANTES.orillanorte!,
    entrega: "Entrega en mano en punto público",
    interesados: 62,
    vistas: 688,
    tono: "mar",
    estadoAnuncio: "reservado",
    ofrece: "Teléfono usado con pantalla sana",
    busca: "Impresora que funcione",
    alternativas: "También acepto recarga de datos móviles",
  },
  {
    id: "art-8",
    titulo: "Juego de sábanas de algodón",
    descripcion: "Cama camera, dos fundas incluidas. Poco uso, sin manchas ni roturas.",
    categoria: "Hogar",
    modo: "venta",
    precio: 3800,
    moneda: "CUP",
    negociable: true,
    estado: "como-nuevo",
    zona: "La Habana",
    pais: "Cuba",
    publicado: "hace 1 día",
    imagenAlt: "Juego de sábanas dobladas de color claro",
    vendedor: ANUNCIANTES.solarhabana!,
    entrega: "Recogida en el barrio o punto acordado",
    interesados: 14,
    vistas: 176,
    tono: "turquesa",
    estadoAnuncio: "activo",
  },
  {
    id: "art-9",
    titulo: "Uniformes escolares de segunda mano",
    descripcion:
      "Cinco uniformes de secundaria en buen estado. Los regalo a familias del barrio; si sobran, van para la escuela.",
    categoria: "Ropa y calzado",
    modo: "donacion",
    estado: "usado",
    zona: "Holguín",
    pais: "Cuba",
    publicado: "hace 3 días",
    imagenAlt: "Uniformes escolares colgados en perchas",
    vendedor: ANUNCIANTES.altamar!,
    entrega: "Coordinado con un promotor de la zona",
    interesados: 27,
    vistas: 310,
    tono: "sol",
    estadoAnuncio: "activo",
    cantidad: "5 uniformes",
    destinatario: "Familias del barrio con niños en secundaria",
  },
  {
    id: "art-10",
    titulo: "Caja de herramientas básica para el hogar",
    descripcion:
      "Alicate, destornilladores, martillo, cinta métrica y llave ajustable. Todo usado pero en buen estado; me mudo y no puedo llevarlo.",
    categoria: "Herramientas",
    modo: "venta",
    precio: 5400,
    moneda: "CUP",
    negociable: true,
    estado: "usado",
    zona: "Camagüey",
    pais: "Cuba",
    publicado: "hace 5 horas",
    imagenAlt: "Caja de herramientas abierta con destornilladores y alicates",
    vendedor: ANUNCIANTES.guajiro!,
    entrega: "Recogida en punto público acordado",
    interesados: 38,
    vistas: 421,
    tono: "madera",
    estadoAnuncio: "activo",
  },
  {
    id: "art-11",
    titulo: "Acompañamiento y toma de presión a domicilio",
    descripcion:
      "Enfermera jubilada. Acompaño a consultas, tomo presión y ayudo con el control de medicamentos de personas mayores. Consultar según la zona.",
    categoria: "Salud y bienestar",
    modo: "servicio",
    estado: "no-aplica",
    zona: "La Habana",
    pais: "Cuba",
    publicado: "hace 12 horas",
    imagenAlt: "Tensiómetro y libreta de control sobre una mesa",
    vendedor: ANUNCIANTES.altamar!,
    entrega: "A domicilio dentro del municipio",
    interesados: 44,
    vistas: 356,
    tono: "turquesa",
    estadoAnuncio: "activo",
    tipoServicio: "Cuidado de personas mayores",
    precioModo: "consultar",
    lugar: "presencial",
    disponibilidad: "Mañanas de lunes a viernes",
  },
  {
    id: "art-12",
    titulo: "Envío de paquete pequeño desde Madrid a La Habana",
    descripcion:
      "Salgo el mes próximo y llevo hasta 5 kg de medicamentos o ropa para familias. No cobro por el favor, sólo coordinamos la recogida.",
    categoria: "Regalos y donaciones",
    modo: "donacion",
    estado: "no-aplica",
    zona: "Madrid",
    pais: "España",
    publicado: "hace 1 día",
    imagenAlt: "Maleta abierta con paquetes pequeños preparados para viajar",
    vendedor: ANUNCIANTES.dosOrillas!,
    entrega: "Recogida en Madrid y entrega en La Habana",
    interesados: 96,
    vistas: 1204,
    tono: "mar",
    estadoAnuncio: "activo",
    cantidad: "Hasta 5 kg",
    destinatario: "Familias que esperan medicamentos o ropa",
  },
  {
    id: "art-13",
    titulo: "Café de la Sierra tostado en casa (libra)",
    descripcion:
      "Café de altura tostado en tanda pequeña. Se muele al pedido. Descuento si traes tu envase.",
    categoria: "Alimentos",
    modo: "venta",
    precio: 1600,
    moneda: "CUP",
    negociable: false,
    estado: "nuevo",
    zona: "Santiago de Cuba",
    pais: "Cuba",
    publicado: "hace 7 horas",
    imagenAlt: "Granos de café tostado en un saco de tela",
    vendedor: ANUNCIANTES.cafeconletras!,
    entrega: "Recogida en el barrio o mensajería local",
    interesados: 58,
    vistas: 640,
    tono: "madera",
    estadoAnuncio: "activo",
  },
  {
    id: "art-14",
    titulo: "Diseño de cartel o menú para tu negocio",
    descripcion:
      "Diseño gráfico sencillo y claro para negocios pequeños: menús, carteles y etiquetas. Trabajo en remoto y envío los archivos listos para imprimir.",
    categoria: "Servicios",
    modo: "servicio",
    precio: 25,
    moneda: "USD",
    estado: "no-aplica",
    zona: "Miami",
    pais: "Estados Unidos",
    publicado: "hace 2 días",
    imagenAlt: "Pantalla con un diseño de menú en proceso",
    vendedor: ANUNCIANTES.orillanorte!,
    entrega: "Entrega de archivos por mensaje",
    interesados: 21,
    vistas: 198,
    tono: "sol",
    estadoAnuncio: "activo",
    tipoServicio: "Diseño gráfico",
    precioModo: "desde",
    lugar: "remoto",
    disponibilidad: "Toda la semana, con respuesta en 48 horas",
  },
  {
    id: "art-15",
    titulo: "Ventilador de pie para piezas",
    descripcion:
      "No enciende, sirve para piezas: aspas, rejilla y base en buen estado. Lo cambio por un cable de extensión o cualquier cosa útil.",
    categoria: "Hogar",
    modo: "intercambio",
    estado: "para-piezas",
    zona: "Matanzas",
    pais: "Cuba",
    publicado: "hace 4 días",
    imagenAlt: "Ventilador de pie desarmado apoyado en una pared",
    vendedor: ANUNCIANTES.solarhabana!,
    entrega: "Recogida en el portal de la casa, en punto acordado",
    interesados: 9,
    vistas: 121,
    tono: "turquesa",
    estadoAnuncio: "activo",
    ofrece: "Ventilador de pie para piezas",
    busca: "Cable de extensión o bombillos",
    alternativas: "Acepto cualquier propuesta razonable",
  },
  {
    id: "art-16",
    titulo: "Taller de costura básica, cuatro sesiones",
    descripcion:
      "Aprender a coser a mano y a máquina lo esencial: dobladillos, botones y arreglos. Grupos de cinco personas, materiales incluidos.",
    categoria: "Formación",
    modo: "servicio",
    precio: 1200,
    moneda: "CUP",
    estado: "no-aplica",
    zona: "Baracoa",
    pais: "Cuba",
    publicado: "hace 3 días",
    imagenAlt: "Máquina de coser con telas y carretes de hilo",
    vendedor: ANUNCIANTES.baracoa!,
    entrega: "Presencial en el local del taller",
    interesados: 33,
    vistas: 287,
    tono: "madera",
    estadoAnuncio: "activo",
    tipoServicio: "Formación práctica",
    precioModo: "fijo",
    lugar: "presencial",
    disponibilidad: "Sábados por la mañana",
  },
];

/** Anuncios de la usuaria de demostración, con estados variados. */
export const MIS_ARTICULOS: Articulo[] = [
  ARTICULOS[1]!,
  ARTICULOS[4]!,
  {
    ...ARTICULOS[7]!,
    id: "mio-1",
    titulo: "Mesa plegable de madera",
    descripcion: "Mesa pequeña de madera dura, plegable. Ideal para espacios reducidos.",
    categoria: "Hogar",
    modo: "venta",
    precio: 7200,
    zona: "Cienfuegos",
    vendedor: ANUNCIANTES.vientodelsur!,
    estadoAnuncio: "reservado",
    interesados: 12,
    vistas: 143,
  },
  {
    ...ARTICULOS[0]!,
    id: "mio-2",
    titulo: "Dulce de guayaba en barra",
    descripcion: "Barras de dulce de guayaba caseras, hechas en tandas pequeñas.",
    categoria: "Alimentos",
    precio: 380,
    zona: "Cienfuegos",
    vendedor: ANUNCIANTES.vientodelsur!,
    estadoAnuncio: "vendido",
    interesados: 30,
    vistas: 402,
  },
  {
    ...ARTICULOS[8]!,
    id: "mio-3",
    titulo: "Zapatos escolares número 34",
    vendedor: ANUNCIANTES.vientodelsur!,
    zona: "Cienfuegos",
    estadoAnuncio: "donado",
    interesados: 18,
    vistas: 210,
  },
  {
    ...ARTICULOS[6]!,
    id: "mio-4",
    titulo: "Libros de secundaria por otros de primaria",
    vendedor: ANUNCIANTES.vientodelsur!,
    zona: "Cienfuegos",
    categoria: "Formación",
    estadoAnuncio: "intercambiado",
    interesados: 7,
    vistas: 96,
  },
  {
    ...ARTICULOS[5]!,
    id: "mio-5",
    titulo: "Cortinas de tela cruda hechas a mano",
    vendedor: ANUNCIANTES.vientodelsur!,
    zona: "Cienfuegos",
    estadoAnuncio: "pausado",
    interesados: 4,
    vistas: 61,
  },
  {
    ...ARTICULOS[9]!,
    id: "mio-6",
    titulo: "Sin título todavía",
    descripcion: "Borrador: falta la descripción y las fotos.",
    vendedor: ANUNCIANTES.vientodelsur!,
    zona: "Cienfuegos",
    estadoAnuncio: "borrador",
    interesados: 0,
    vistas: 0,
  },
];

export type OpinionMercadito = {
  id: string;
  alias: string;
  autor: string;
  avatar: string;
  estrellas: number;
  fecha: string;
  texto: string;
};

export const OPINIONES_MERCADITO: OpinionMercadito[] = [
  {
    id: "op-1",
    alias: "vientodelsur",
    autor: "orillanorte",
    avatar: "MT",
    estrellas: 5,
    fecha: "hace 2 semanas",
    texto: "Todo tal como lo describió. Coordinamos en un punto público y fue rápido.",
  },
  {
    id: "op-2",
    alias: "vientodelsur",
    autor: "Lisbet Ferrer",
    avatar: "LF",
    estrellas: 5,
    fecha: "hace 1 mes",
    texto: "Muy clara con los horarios de las clases. Mi hijo mejoró bastante.",
  },
  {
    id: "op-3",
    alias: "mango-y-miel",
    autor: "cafeconletras",
    avatar: "EV",
    estrellas: 5,
    fecha: "hace 3 días",
    texto: "La mermelada llegó bien sellada y el frasco retornable es un detalle enorme.",
  },
  {
    id: "op-4",
    alias: "guajiroconwifi",
    autor: "Dayana Cruz",
    avatar: "DC",
    estrellas: 4,
    fecha: "hace 3 semanas",
    texto: "El intercambio se demoró un poco en cuadrar, pero cumplió lo acordado.",
  },
];

export const MOTIVOS_DENUNCIA = [
  "Posible fraude",
  "Producto prohibido",
  "Información engañosa",
  "Suplantación",
  "Acoso",
  "Datos personales expuestos",
  "Contenido duplicado",
  "Otro",
];

export const CONSEJOS_SEGURIDAD = [
  "No compartas contraseñas ni códigos de seguridad.",
  "No publiques tu dirección exacta.",
  "Comprueba la identidad pública y la reputación antes de cerrar un trato.",
  "No envíes dinero fuera de mecanismos autorizados.",
  "Denuncia comportamientos sospechosos.",
];

export function buscarArticulo(id: string) {
  return [...ARTICULOS, ...MIS_ARTICULOS].find((a) => a.id === id);
}

export function opinionesDe(alias: string) {
  return OPINIONES_MERCADITO.filter((o) => o.alias === alias);
}
