import type { Autor, Publicacion } from "../tipos";

const autor = (
  alias: string,
  nombreVisible: string,
  avatar: string,
  mostrarComo: Autor["mostrarComo"] = "alias",
  insignias: Autor["insignias"] = [],
  enlace = `/perfil/${alias}`,
): Autor => ({ alias, nombreVisible, avatar, mostrarComo, insignias, enlace });

export const PUBLICACIONES: Publicacion[] = [
  {
    id: "pub-1",
    tipo: "texto",
    autor: autor("vientodelsur", "vientodelsur", "YM", "alias", ["verificado"]),
    fecha: "hace 20 minutos",
    ubicacion: "Cienfuegos",
    audiencia: "comunidad",
    texto:
      "Hoy en el aula aparecieron doce libretas nuevas que nadie firmó. Alguien de esta comunidad las dejó en la escuela y se fue sin decir su nombre. Gracias, quien quiera que seas: los muchachos escribieron toda la mañana.",
    reacciones: { gusta: 128, inspira: 64, apoyo: 21, gracias: 90, interesa: 4 },
    comentarios: [
      {
        id: "c-1",
        autor: autor("solarhabana", "Lisbet Ferrer", "LF", "nombre"),
        fecha: "hace 12 minutos",
        texto:
          "Esto es lo que quiero leer por las mañanas. Si hacen falta lápices, tengo una caja.",
      },
    ],
    guardados: 12,
    compartidos: 8,
    temas: ["Comunidad", "Educación"],
  },
  {
    id: "pub-2",
    tipo: "campana",
    autor: autor("manosdealtamar", "Dayana Cruz", "DC", "nombre", ["promotor", "solidario"]),
    fecha: "hace 1 hora",
    ubicacion: "Villa Clara",
    audiencia: "comunidad",
    texto:
      "Abrimos la recogida para el consultorio del reparto Sakenaf: hacen falta guantes, gasas y tensiómetros. Todo lo que entre se entrega con acta firmada y se publica aquí mismo.",
    adjunto: {
      titulo: "Insumos básicos para el consultorio de Sakenaf",
      detalle: "Campaña verificada · Entrega estimada: 12 de septiembre",
      enlace: "/campana/cmp-1",
      etiqueta: "La Mano",
    },
    reacciones: { gusta: 54, inspira: 40, apoyo: 187, gracias: 62, interesa: 15 },
    comentarios: [],
    guardados: 44,
    compartidos: 37,
    temas: ["Ayuda", "Salud"],
  },
  {
    id: "pub-3",
    tipo: "producto",
    autor: autor("guajiroconwifi", "guajiroconwifi", "RP", "alias"),
    fecha: "hace 2 horas",
    ubicacion: "Sancti Spíritus",
    audiencia: "comunidad",
    texto:
      "Terminé de restaurar esta bicicleta eléctrica: batería nueva, frenos revisados y luces. La cambio por una nevera pequeña que funcione o la vendo.",
    imagenes: [{ url: "madera", alt: "Bicicleta eléctrica restaurada apoyada en un portal" }],
    adjunto: {
      titulo: "Bicicleta eléctrica restaurada",
      detalle: "Intercambio o venta · Sancti Spíritus",
      enlace: "/producto/art-3",
      etiqueta: "El Mercadito",
    },
    reacciones: { gusta: 61, inspira: 12, apoyo: 5, gracias: 3, interesa: 74 },
    comentarios: [
      {
        id: "c-2",
        autor: autor("orillanorte", "orillanorte", "MT", "alias"),
        fecha: "hace 1 hora",
        texto: "¿Le pusiste batería de litio o de gel? Pregunto para una igual que tengo parada.",
      },
    ],
    guardados: 30,
    compartidos: 6,
    temas: ["Emprendimiento", "Transporte"],
  },
  {
    id: "pub-4",
    tipo: "encuesta",
    autor: autor("cafeconletras", "cafeconletras", "EV", "alias", ["verificado"]),
    fecha: "hace 3 horas",
    audiencia: "comunidad",
    texto:
      "Para quienes emprenden en la Isla: ¿qué les frena más ahora mismo? Respondan sin discutir a nadie, que la idea es entendernos.",
    encuesta: [
      { texto: "Conseguir materia prima", votos: 412 },
      { texto: "Los trámites", votos: 265 },
      { texto: "El transporte", votos: 198 },
      { texto: "Cobrar y pagar", votos: 331 },
    ],
    reacciones: { gusta: 44, inspira: 9, apoyo: 18, gracias: 6, interesa: 121 },
    comentarios: [],
    guardados: 21,
    compartidos: 11,
    temas: ["Opinión", "Emprendimiento"],
  },
  {
    id: "pub-5",
    tipo: "empleo",
    autor: autor(
      "colmena-mangoymiel",
      "Mango y Miel",
      "MM",
      "negocio",
      ["negocio", "verificado"],
      "/negocio/mango-y-miel",
    ),
    fecha: "hace 5 horas",
    ubicacion: "Matanzas",
    audiencia: "comunidad",
    texto:
      "Buscamos dos personas para nuestro taller de mermeladas en Matanzas. No pedimos experiencia: enseñamos nosotros. Turnos de mañana y merienda incluida.",
    adjunto: {
      titulo: "Ayudante de taller · Mango y Miel",
      detalle: "Presencial · Matanzas · Sin experiencia",
      enlace: "/taller",
      etiqueta: "El Taller",
    },
    reacciones: { gusta: 39, inspira: 22, apoyo: 8, gracias: 4, interesa: 143 },
    comentarios: [],
    guardados: 58,
    compartidos: 19,
    temas: ["Empleo", "Emprendimiento"],
  },
  {
    id: "pub-6",
    tipo: "opinion",
    autor: autor("cafeconletras", "cafeconletras", "EV", "alias", ["verificado"]),
    fecha: "hace 7 horas",
    audiencia: "comunidad",
    texto:
      "Escribí una nota sobre por qué la ayuda que se explica dura más que la ayuda que se presume. No hace falta estar de acuerdo conmigo; hace falta que discutamos sin arrancarle la cabeza a nadie.",
    adjunto: {
      titulo: "La ayuda que se explica",
      detalle: "Artículo · 6 minutos de lectura",
      enlace: "/la-esquina",
      etiqueta: "La Esquina",
    },
    reacciones: { gusta: 87, inspira: 55, apoyo: 12, gracias: 9, interesa: 33 },
    comentarios: [],
    guardados: 40,
    compartidos: 27,
    temas: ["Opinión"],
  },
  {
    id: "pub-7",
    tipo: "foto",
    autor: autor("solarhabana", "Lisbet Ferrer", "LF", "nombre"),
    fecha: "hace 9 horas",
    ubicacion: "La Habana",
    audiencia: "conexiones",
    texto:
      "Sábado de clase de diseño en el solar. Ocho vecinas aprendieron a hacer el cartel de su negocio con el móvil. La próxima es sobre fotos de producto.",
    imagenes: [
      { url: "turquesa", alt: "Grupo de vecinas alrededor de una mesa con teléfonos y cuadernos" },
      { url: "sol", alt: "Cartel casero de una dulcería hecho durante el taller" },
    ],
    reacciones: { gusta: 152, inspira: 96, apoyo: 14, gracias: 31, interesa: 12 },
    comentarios: [],
    guardados: 26,
    compartidos: 14,
    temas: ["Formación", "Comunidad"],
  },
  {
    id: "pub-8",
    tipo: "comunidad",
    autor: autor(
      "barrio-holguin",
      "Holguineros en cualquier parte",
      "HO",
      "negocio",
      [],
      "/mi-barrio",
    ),
    fecha: "hace 12 horas",
    audiencia: "barrio",
    texto:
      "Este mes el grupo cumple 100 miembros. Abrimos un hilo para que cada quien cuente qué sabe hacer: así encontramos ayuda dentro de casa antes de buscarla fuera.",
    reacciones: { gusta: 74, inspira: 38, apoyo: 20, gracias: 11, interesa: 46 },
    comentarios: [],
    guardados: 9,
    compartidos: 22,
    temas: ["Comunidad"],
  },
  {
    id: "pub-9",
    tipo: "servicio",
    autor: autor("orillanorte", "orillanorte", "MT", "alias", ["solidario"]),
    fecha: "hace 1 día",
    audiencia: "comunidad",
    texto:
      "Ofrezco dos horas semanales de mentoría gratuita para quien esté aprendiendo programación desde Cuba. No prometo trabajo; prometo acompañarte y revisar lo que hagas.",
    adjunto: {
      titulo: "Mentoría en programación web",
      detalle: "Remoto · 2 plazas al mes",
      enlace: "/taller",
      etiqueta: "El Taller",
    },
    reacciones: { gusta: 118, inspira: 77, apoyo: 25, gracias: 61, interesa: 204 },
    comentarios: [],
    guardados: 133,
    compartidos: 48,
    temas: ["Empleo", "Formación"],
  },
  {
    id: "pub-10",
    tipo: "negocio",
    autor: autor(
      "colmena-taller-almendares",
      "Taller Almendares",
      "TA",
      "negocio",
      ["negocio", "solidario"],
      "/negocio/taller-almendares",
    ),
    fecha: "hace 1 día",
    ubicacion: "La Habana",
    audiencia: "comunidad",
    texto:
      "Cerramos el mes reparando gratis 14 ventiladores de personas mayores del municipio. Publicamos el listado por número de orden, sin nombres ni direcciones, como pidió la comunidad.",
    reacciones: { gusta: 96, inspira: 71, apoyo: 34, gracias: 145, interesa: 18 },
    comentarios: [],
    guardados: 17,
    compartidos: 29,
    temas: ["Emprendimiento", "Ayuda"],
  },
];

export const FILTROS_MURO = [
  { clave: "para-ti", etiqueta: "Para ti" },
  { clave: "siguiendo", etiqueta: "Siguiendo" },
  { clave: "cuba", etiqueta: "Cuba" },
  { clave: "mi-comunidad", etiqueta: "Mi comunidad" },
  { clave: "ayuda", etiqueta: "Ayuda" },
  { clave: "emprendimiento", etiqueta: "Emprendimiento" },
  { clave: "opinion", etiqueta: "Opinión" },
] as const;

export type FiltroMuro = (typeof FILTROS_MURO)[number]["clave"];
