import type { Oportunidad, TipoOportunidad } from "../tipos";

export const TIPOS_OPORTUNIDAD: Record<TipoOportunidad, string> = {
  empleo: "Empleo",
  temporal: "Trabajo temporal",
  servicio: "Servicio profesional",
  mentoria: "Mentoría",
  curso: "Curso",
  beca: "Beca",
  recurso: "Recurso para recién llegados",
};

export const OPORTUNIDADES: Oportunidad[] = [
  {
    id: "opo-1",
    titulo: "Ayudante de taller de mermeladas",
    entidad: "Mango y Miel",
    tipo: "empleo",
    pais: "Cuba",
    modalidad: "presencial",
    sector: "Alimentación",
    experiencia: "sin-experiencia",
    resumen: "Dos plazas en Matanzas. Enseñamos el oficio desde el primer día.",
    descripcion:
      "Trabajarás en la preparación, envasado y etiquetado de mermeladas artesanales. Turnos de mañana, merienda incluida y un día libre a la semana además del domingo.",
    requisitos: ["Ganas de aprender", "Puntualidad", "Vivir cerca de Matanzas ciudad"],
    publicado: "hace 5 horas",
    compensacion: "Salario acordado por escrito antes de empezar",
    interesados: 143,
  },
  {
    id: "opo-2",
    titulo: "Mentoría en programación web",
    entidad: "orillanorte",
    tipo: "mentoria",
    pais: "Internacional",
    modalidad: "remoto",
    sector: "Tecnología",
    experiencia: "inicial",
    resumen: "Dos horas semanales de acompañamiento para quien estudia por su cuenta.",
    descripcion:
      "Revisamos tu código, te propongo ejercicios y preparamos juntos un pequeño portafolio. No hay promesa de empleo, sí compromiso de constancia.",
    requisitos: ["Conexión al menos una vez por semana", "Haber empezado con HTML y CSS"],
    publicado: "hace 1 día",
    compensacion: "Gratuito",
    interesados: 204,
  },
  {
    id: "opo-3",
    titulo: "Curso de contabilidad para emprendedores",
    entidad: "La Colmena · Formación",
    tipo: "curso",
    pais: "Cuba",
    modalidad: "mixto",
    sector: "Negocios",
    experiencia: "sin-experiencia",
    resumen: "Seis sesiones para llevar las cuentas de un negocio pequeño sin perderse.",
    descripcion:
      "Cuentas básicas, control de gastos, precios y cómo separar el dinero del negocio del dinero de la casa. Material en PDF descargable.",
    requisitos: ["Tener o querer abrir un negocio", "Cuaderno y calculadora"],
    publicado: "hace 3 días",
    compensacion: "Gratuito para miembros de La Colmena",
    interesados: 88,
  },
  {
    id: "opo-4",
    titulo: "Diseñador gráfico por proyecto",
    entidad: "Manos de Baracoa",
    tipo: "servicio",
    pais: "Cuba",
    modalidad: "remoto",
    sector: "Diseño",
    experiencia: "intermedia",
    resumen: "Catálogo de artesanía y etiquetas para diez productos.",
    descripcion:
      "Buscamos a alguien que nos ayude con el catálogo digital y las etiquetas. Entrega en tres semanas, pago por proyecto.",
    requisitos: ["Portafolio con trabajos anteriores", "Manejo de un editor gráfico"],
    publicado: "hace 2 días",
    compensacion: "Pago por proyecto acordado por escrito",
    interesados: 37,
  },
  {
    id: "opo-5",
    titulo: "Beca de estudio en oficios técnicos",
    entidad: "Fundación Dos Orillas",
    tipo: "beca",
    pais: "España",
    modalidad: "presencial",
    sector: "Formación técnica",
    experiencia: "sin-experiencia",
    resumen: "Diez plazas para cubanos residentes en España en electricidad y climatización.",
    descripcion:
      "Formación de seis meses con prácticas. Incluye material y transporte. Se valora la situación de la persona, no su posición política.",
    requisitos: ["Residir en España", "Mayor de 18 años", "Compromiso de asistencia"],
    publicado: "hace 6 días",
    compensacion: "Beca de estudio y material incluido",
    interesados: 121,
  },
  {
    id: "opo-6",
    titulo: "Apoyo temporal en mudanzas y montaje",
    entidad: "Cooperativa El Almendrón",
    tipo: "temporal",
    pais: "Cuba",
    modalidad: "presencial",
    sector: "Servicios",
    experiencia: "sin-experiencia",
    resumen: "Trabajo por jornadas sueltas en La Habana.",
    descripcion: "Se avisa con dos días de antelación. Pago al terminar cada jornada.",
    requisitos: ["Mayor de 18 años", "Buena forma física"],
    publicado: "hace 12 horas",
    compensacion: "Pago por jornada",
    interesados: 66,
  },
  {
    id: "opo-7",
    titulo: "Guía práctica para recién llegados",
    entidad: "Mis Caminos · Recursos",
    tipo: "recurso",
    pais: "Internacional",
    modalidad: "remoto",
    sector: "Acompañamiento",
    experiencia: "sin-experiencia",
    resumen: "Qué hacer las primeras semanas fuera de Cuba, contado por quien ya pasó por ahí.",
    descripcion:
      "Trámites frecuentes, dónde pedir ayuda, cómo homologar estudios y cómo cuidar la salud mental en la mudanza.",
    requisitos: [],
    publicado: "hace 1 semana",
    compensacion: "Gratuito",
    interesados: 310,
  },
  {
    id: "opo-8",
    titulo: "Atención al cliente en tienda en línea",
    entidad: "Dos Orillas Envíos",
    tipo: "empleo",
    pais: "Internacional",
    modalidad: "remoto",
    sector: "Comercio",
    experiencia: "inicial",
    resumen: "Turnos de tarde respondiendo mensajes de clientes cubanos.",
    descripcion:
      "Atención por escrito, sin llamadas. Se valora la paciencia y el trato cuidadoso con familias que envían ayuda.",
    requisitos: ["Conexión estable", "Buena redacción en español"],
    publicado: "hace 4 días",
    compensacion: "Salario mensual acordado por contrato",
    interesados: 178,
  },
];

export function buscarOportunidad(id: string) {
  return OPORTUNIDADES.find((o) => o.id === id);
}