/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColmenaRouteImport } from './routes/colmena'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as LaEsquinaRouteImport } from './routes/la-esquina'
import { Route as LaManoRouteImport } from './routes/la-mano'
import { Route as MaleconRouteImport } from './routes/malecon'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as MercaditoRouteImport } from './routes/mercadito'
import { Route as MiBarrioRouteImport } from './routes/mi-barrio'
import { Route as MiChivichanaRouteImport } from './routes/mi-chivichana'
import { Route as MisCaminosRouteImport } from './routes/mis-caminos'
import { Route as NormasRouteImport } from './routes/normas'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PromotoresRouteImport } from './routes/promotores'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as MercaditoIndexRouteImport } from './routes/mercadito.index'
import { Route as MercaditoGuardadosRouteImport } from './routes/mercadito.guardados'
import { Route as MercaditoMisPublicacionesRouteImport } from './routes/mercadito.mis-publicaciones'
import { Route as MercaditoPublicarRouteImport } from './routes/mercadito.publicar'
import { Route as NegocioSlugRouteImport } from './routes/negocio.$slug'
import { Route as PerfilAliasRouteImport } from './routes/perfil.$alias'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as ProductoIdEditarRouteImport } from './routes/producto.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColmenaRoute = ColmenaRouteImport.update({
  id: '/colmena',
  path: '/colmena',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LaEsquinaRoute = LaEsquinaRouteImport.update({
  id: '/la-esquina',
  path: '/la-esquina',
  getParentRoute: () => rootRouteImport,
} as any)
const LaManoRoute = LaManoRouteImport.update({
  id: '/la-mano',
  path: '/la-mano',
  getParentRoute: () => rootRouteImport,
} as any)
const MaleconRoute = MaleconRouteImport.update({
  id: '/malecon',
  path: '/malecon',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const MercaditoRoute = MercaditoRouteImport.update({
  id: '/mercadito',
  path: '/mercadito',
  getParentRoute: () => rootRouteImport,
} as any)
const MiBarrioRoute = MiBarrioRouteImport.update({
  id: '/mi-barrio',
  path: '/mi-barrio',
  getParentRoute: () => rootRouteImport,
} as any)
const MiChivichanaRoute = MiChivichanaRouteImport.update({
  id: '/mi-chivichana',
  path: '/mi-chivichana',
  getParentRoute: () => rootRouteImport,
} as any)
const MisCaminosRoute = MisCaminosRouteImport.update({
  id: '/mis-caminos',
  path: '/mis-caminos',
  getParentRoute: () => rootRouteImport,
} as any)
const NormasRoute = NormasRouteImport.update({
  id: '/normas',
  path: '/normas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotoresRoute = PromotoresRouteImport.update({
  id: '/promotores',
  path: '/promotores',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const MercaditoIndexRoute = MercaditoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MercaditoRoute,
} as any)
const MercaditoGuardadosRoute = MercaditoGuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => MercaditoRoute,
} as any)
const MercaditoMisPublicacionesRoute =
  MercaditoMisPublicacionesRouteImport.update({
    id: '/mis-publicaciones',
    path: '/mis-publicaciones',
    getParentRoute: () => MercaditoRoute,
  } as any)
const MercaditoPublicarRoute = MercaditoPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => MercaditoRoute,
} as any)
const NegocioSlugRoute = NegocioSlugRouteImport.update({
  id: '/negocio/$slug',
  path: '/negocio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilAliasRoute = PerfilAliasRouteImport.update({
  id: '/perfil/$alias',
  path: '/perfil/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdEditarRoute = ProductoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ProductoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colmena': typeof ColmenaRoute
  '/entrar': typeof EntrarRoute
  '/la-esquina': typeof LaEsquinaRoute
  '/la-mano': typeof LaManoRoute
  '/malecon': typeof MaleconRoute
  '/mensajes': typeof MensajesRoute
  '/mercadito': typeof MercaditoRouteWithChildren
  '/mi-barrio': typeof MiBarrioRoute
  '/mi-chivichana': typeof MiChivichanaRoute
  '/mis-caminos': typeof MisCaminosRoute
  '/normas': typeof NormasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/promotores': typeof PromotoresRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/taller': typeof TallerRoute
  '/mercadito/guardados': typeof MercaditoGuardadosRoute
  '/mercadito/mis-publicaciones': typeof MercaditoMisPublicacionesRoute
  '/mercadito/publicar': typeof MercaditoPublicarRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/perfil/$alias': typeof PerfilAliasRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/mercadito/': typeof MercaditoIndexRoute
  '/producto/$id/editar': typeof ProductoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colmena': typeof ColmenaRoute
  '/entrar': typeof EntrarRoute
  '/la-esquina': typeof LaEsquinaRoute
  '/la-mano': typeof LaManoRoute
  '/malecon': typeof MaleconRoute
  '/mensajes': typeof MensajesRoute
  '/mi-barrio': typeof MiBarrioRoute
  '/mi-chivichana': typeof MiChivichanaRoute
  '/mis-caminos': typeof MisCaminosRoute
  '/normas': typeof NormasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/promotores': typeof PromotoresRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/taller': typeof TallerRoute
  '/mercadito/guardados': typeof MercaditoGuardadosRoute
  '/mercadito/mis-publicaciones': typeof MercaditoMisPublicacionesRoute
  '/mercadito/publicar': typeof MercaditoPublicarRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/perfil/$alias': typeof PerfilAliasRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/mercadito': typeof MercaditoIndexRoute
  '/producto/$id/editar': typeof ProductoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colmena': typeof ColmenaRoute
  '/entrar': typeof EntrarRoute
  '/la-esquina': typeof LaEsquinaRoute
  '/la-mano': typeof LaManoRoute
  '/malecon': typeof MaleconRoute
  '/mensajes': typeof MensajesRoute
  '/mercadito': typeof MercaditoRouteWithChildren
  '/mi-barrio': typeof MiBarrioRoute
  '/mi-chivichana': typeof MiChivichanaRoute
  '/mis-caminos': typeof MisCaminosRoute
  '/normas': typeof NormasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/promotores': typeof PromotoresRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/taller': typeof TallerRoute
  '/mercadito/guardados': typeof MercaditoGuardadosRoute
  '/mercadito/mis-publicaciones': typeof MercaditoMisPublicacionesRoute
  '/mercadito/publicar': typeof MercaditoPublicarRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/perfil/$alias': typeof PerfilAliasRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/mercadito/': typeof MercaditoIndexRoute
  '/producto/$id/editar': typeof ProductoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colmena'
    | '/entrar'
    | '/la-esquina'
    | '/la-mano'
    | '/malecon'
    | '/mensajes'
    | '/mercadito'
    | '/mi-barrio'
    | '/mi-chivichana'
    | '/mis-caminos'
    | '/normas'
    | '/notificaciones'
    | '/privacidad'
    | '/promotores'
    | '/publicar'
    | '/registro'
    | '/taller'
    | '/mercadito/guardados'
    | '/mercadito/mis-publicaciones'
    | '/mercadito/publicar'
    | '/negocio/$slug'
    | '/perfil/$alias'
    | '/producto/$id'
    | '/mercadito/'
    | '/producto/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colmena'
    | '/entrar'
    | '/la-esquina'
    | '/la-mano'
    | '/malecon'
    | '/mensajes'
    | '/mi-barrio'
    | '/mi-chivichana'
    | '/mis-caminos'
    | '/normas'
    | '/notificaciones'
    | '/privacidad'
    | '/promotores'
    | '/publicar'
    | '/registro'
    | '/taller'
    | '/mercadito/guardados'
    | '/mercadito/mis-publicaciones'
    | '/mercadito/publicar'
    | '/negocio/$slug'
    | '/perfil/$alias'
    | '/producto/$id'
    | '/mercadito'
    | '/producto/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/colmena'
    | '/entrar'
    | '/la-esquina'
    | '/la-mano'
    | '/malecon'
    | '/mensajes'
    | '/mercadito'
    | '/mi-barrio'
    | '/mi-chivichana'
    | '/mis-caminos'
    | '/normas'
    | '/notificaciones'
    | '/privacidad'
    | '/promotores'
    | '/publicar'
    | '/registro'
    | '/taller'
    | '/mercadito/guardados'
    | '/mercadito/mis-publicaciones'
    | '/mercadito/publicar'
    | '/negocio/$slug'
    | '/perfil/$alias'
    | '/producto/$id'
    | '/mercadito/'
    | '/producto/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColmenaRoute: typeof ColmenaRoute
  EntrarRoute: typeof EntrarRoute
  LaEsquinaRoute: typeof LaEsquinaRoute
  LaManoRoute: typeof LaManoRoute
  MaleconRoute: typeof MaleconRoute
  MensajesRoute: typeof MensajesRoute
  MercaditoRoute: typeof MercaditoRouteWithChildren
  MiBarrioRoute: typeof MiBarrioRoute
  MiChivichanaRoute: typeof MiChivichanaRoute
  MisCaminosRoute: typeof MisCaminosRoute
  NormasRoute: typeof NormasRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  PromotoresRoute: typeof PromotoresRoute
  PublicarRoute: typeof PublicarRoute
  RegistroRoute: typeof RegistroRoute
  TallerRoute: typeof TallerRoute
  NegocioSlugRoute: typeof NegocioSlugRoute
  PerfilAliasRoute: typeof PerfilAliasRoute
  ProductoIdRoute: typeof ProductoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colmena': {
      id: '/colmena'
      path: '/colmena'
      fullPath: '/colmena'
      preLoaderRoute: typeof ColmenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-esquina': {
      id: '/la-esquina'
      path: '/la-esquina'
      fullPath: '/la-esquina'
      preLoaderRoute: typeof LaEsquinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-mano': {
      id: '/la-mano'
      path: '/la-mano'
      fullPath: '/la-mano'
      preLoaderRoute: typeof LaManoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malecon': {
      id: '/malecon'
      path: '/malecon'
      fullPath: '/malecon'
      preLoaderRoute: typeof MaleconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercadito': {
      id: '/mercadito'
      path: '/mercadito'
      fullPath: '/mercadito'
      preLoaderRoute: typeof MercaditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-barrio': {
      id: '/mi-barrio'
      path: '/mi-barrio'
      fullPath: '/mi-barrio'
      preLoaderRoute: typeof MiBarrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-chivichana': {
      id: '/mi-chivichana'
      path: '/mi-chivichana'
      fullPath: '/mi-chivichana'
      preLoaderRoute: typeof MiChivichanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-caminos': {
      id: '/mis-caminos'
      path: '/mis-caminos'
      fullPath: '/mis-caminos'
      preLoaderRoute: typeof MisCaminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normas': {
      id: '/normas'
      path: '/normas'
      fullPath: '/normas'
      preLoaderRoute: typeof NormasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotores': {
      id: '/promotores'
      path: '/promotores'
      fullPath: '/promotores'
      preLoaderRoute: typeof PromotoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercadito/': {
      id: '/mercadito/'
      path: '/'
      fullPath: '/mercadito/'
      preLoaderRoute: typeof MercaditoIndexRouteImport
      parentRoute: typeof MercaditoRoute
    }
    '/mercadito/guardados': {
      id: '/mercadito/guardados'
      path: '/guardados'
      fullPath: '/mercadito/guardados'
      preLoaderRoute: typeof MercaditoGuardadosRouteImport
      parentRoute: typeof MercaditoRoute
    }
    '/mercadito/mis-publicaciones': {
      id: '/mercadito/mis-publicaciones'
      path: '/mis-publicaciones'
      fullPath: '/mercadito/mis-publicaciones'
      preLoaderRoute: typeof MercaditoMisPublicacionesRouteImport
      parentRoute: typeof MercaditoRoute
    }
    '/mercadito/publicar': {
      id: '/mercadito/publicar'
      path: '/publicar'
      fullPath: '/mercadito/publicar'
      preLoaderRoute: typeof MercaditoPublicarRouteImport
      parentRoute: typeof MercaditoRoute
    }
    '/negocio/$slug': {
      id: '/negocio/$slug'
      path: '/negocio/$slug'
      fullPath: '/negocio/$slug'
      preLoaderRoute: typeof NegocioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$alias': {
      id: '/perfil/$alias'
      path: '/perfil/$alias'
      fullPath: '/perfil/$alias'
      preLoaderRoute: typeof PerfilAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id/editar': {
      id: '/producto/$id/editar'
      path: '/editar'
      fullPath: '/producto/$id/editar'
      preLoaderRoute: typeof ProductoIdEditarRouteImport
      parentRoute: typeof ProductoIdRoute
    }
  }
}

interface MercaditoRouteChildren {
  MercaditoGuardadosRoute: typeof MercaditoGuardadosRoute
  MercaditoMisPublicacionesRoute: typeof MercaditoMisPublicacionesRoute
  MercaditoPublicarRoute: typeof MercaditoPublicarRoute
  MercaditoIndexRoute: typeof MercaditoIndexRoute
}

const MercaditoRouteChildren: MercaditoRouteChildren = {
  MercaditoGuardadosRoute: MercaditoGuardadosRoute,
  MercaditoMisPublicacionesRoute: MercaditoMisPublicacionesRoute,
  MercaditoPublicarRoute: MercaditoPublicarRoute,
  MercaditoIndexRoute: MercaditoIndexRoute,
}

const MercaditoRouteWithChildren = MercaditoRoute._addFileChildren(
  MercaditoRouteChildren,
)

interface ProductoIdRouteChildren {
  ProductoIdEditarRoute: typeof ProductoIdEditarRoute
}

const ProductoIdRouteChildren: ProductoIdRouteChildren = {
  ProductoIdEditarRoute: ProductoIdEditarRoute,
}

const ProductoIdRouteWithChildren = ProductoIdRoute._addFileChildren(
  ProductoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColmenaRoute: ColmenaRoute,
  EntrarRoute: EntrarRoute,
  LaEsquinaRoute: LaEsquinaRoute,
  LaManoRoute: LaManoRoute,
  MaleconRoute: MaleconRoute,
  MensajesRoute: MensajesRoute,
  MercaditoRoute: MercaditoRouteWithChildren,
  MiBarrioRoute: MiBarrioRoute,
  MiChivichanaRoute: MiChivichanaRoute,
  MisCaminosRoute: MisCaminosRoute,
  NormasRoute: NormasRoute,
  NotificacionesRoute: NotificacionesRoute,
  PrivacidadRoute: PrivacidadRoute,
  PromotoresRoute: PromotoresRoute,
  PublicarRoute: PublicarRoute,
  RegistroRoute: RegistroRoute,
  TallerRoute: TallerRoute,
  NegocioSlugRoute: NegocioSlugRoute,
  PerfilAliasRoute: PerfilAliasRoute,
  ProductoIdRoute: ProductoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
